name = "our-wedding-day"
type = "javascript"

account_id = "our.mobile.wedding@gmail.com"
zone_id = "our.mobile.wedding"
route = "http://our-wedding-day.com/*"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
