export const icons = {
  kakao: "/img/kakao.webp",
  naver: "/img/naver.webp",
  tmap: "/img/tmap.webp",
  bus: "/img/bus.webp",
  car: "/img/car.webp",
  subway: "/img/subway.webp",
  location: "/img/location.webp",
  lock: "/img/lock.webp",
  unlock: "/img/unlock.webp",
  moreButton: "/img/MoreButton.webp",
  heart: "/img/heart.webp",
  flower: "/img/flower.webp",
  leaf: "/img/leaf.webp",
  play: "/img/play.webp",
  stop: "/img/stop.webp",
  invatationImg: "/gallery/full/image31.webp",
  MainImage: "/img/MainImage.webp",
};
