export const icons = {
  kakao: "/img/kakao.webp",
  naver: "/img/naver.webp",
  tmap: "/img/tmap.webp",
  bus: "/img/bus.webp",
  car: "/img/car.webp",
  subway: "/img/subway.webp",
  location: "/img/location.webp",
  lock: "/img/lock.webp",
  unlock: "/img/unlock.webp",
  mute: "/img/mute3.webp",
  sound: "/img/sound2.webp",
  moreButton: "/img/MoreButton.webp",
  heart: "/img/heart.webp",
  heart1: "/img/heart1.webp",
  flower: "/img/flower.webp",
  leaf: "/img/leaf.webp",
  invitation0: "/img/Invitation.webp",
  invitation1: "/img/Invitation1.webp",
  invitation2: "/img/Invitation2.webp",
  invitation3: "/img/Invitation3.webp",
  invitation4: "/img/Invitation4.webp",
  invitation5: "/img/Invitation5.webp",
  test1: "/img/test1.webp",
  test2: "/img/test2.webp",
  invatationImg: "/gallery/full/image31.webp",
};
